image:
  repository: abderrahim98/complete-devops-project
  tag: "5fa58d4"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
httpRoute:
  enabled: false
serviceAccount:
  enable: false
autoscaling:
  enable: false
