image:
  repository: abderrahimx05/complete-devops-project/actions
  tag: 8987aae
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enable: false
autoscaling:
  enable: false
